# Generated by Django 3.2 on 2023-02-23 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='\n        Telefon raqam: 13 ta belgidan iborat bolishi kerak. P.s: +998912345678\n    ', regex='^[+]998\\d{9}$')])),
                ('donate_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('donate_type', models.CharField(blank=True, choices=[('n', 'Naqt'), ('s', "Pul o'tkazish"), ('c', 'Chek')], max_length=1)),
                ('spent_money', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_legal_entity', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('n', 'Yangi'), ('m', 'Moderatsiyada'), ('a', 'Tasdiqlangan'), ('r', 'Bekor qilingan')], default='n', max_length=1)),
                ('is_delete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
