# Generated by Django 3.2 on 2023-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='higheduinstitution',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
